version: '2'
services:
  jenkins:
    image: jenkins:latest
    depends_on:
      - nexus
      - gitlab
    ports:
       - 8082:8080
    volumes:
      - ./jenkins/config/settings.xml:/var/jenkins_home/settings.xml
    links:
      - nexus
      - gitlab
  nexus:
    image: sonatype/nexus:oss
    volumes:
      - ./nexus/volumes:/usr/local/tomcat/conf/server.xml
    ports:
      - 8081:8081
#    environment:
#      - JAVA_OPTS=-verbose:gc -XX:+UseParallelGC -Xms1g -Xmx1g -XX:+PrintFlagsFinal
  gitlab:
      image: gitlab/gitlab-ce
      volumes:
        - ./gitlab/volumes/config:/etc/gitlab
        - ./gitlab/volumes/data:/var/opt/gitlab
        - ./gitlab/volumes/logs:/var/log/gitlab
      ports:
        - "8083:80"
        - "8443:443"
        - "8022:22"
